/* ========================================================
   APIKnow - 数据层 (data.js)
   ========================================================
   修改说明：
   1. 改价格：直接修改 provider 对象的 pricing 字段
   2. 添加新服务商：复制一个对象，修改字段，加入 providers 数组
   3. 修改状态：改 statusKeys 数组
   4. 添加新测评：在 reviews 数组末尾添加新对象
   ======================================================== */

/* ---------------- 状态枚举 ---------------- */
const STATUS_CONFIG = {
  VERIFIED:  { label: '实测稳定',  cls: 'badge-verified',  icon: '&#10004;', desc: '经过实测验证，价格与接口稳定' },
  FLOATING:  { label: '价格浮动',  cls: 'badge-floating',  icon: '&#9888;', desc: '价格近期有波动，建议下单前确认' },
  RISK:      { label: '风险中转',  cls: 'badge-risk',      icon: '&#10008;', desc: '中转代理，存在封号、断供风险' },
  TRIAL:     { label: '支持试用',  cls: 'badge-trial',     icon: '&#9733;', desc: '提供免费额度或试用期，可先行测试' },
  SPONSORED: { label: '商家赞助',  cls: 'badge-sponsored', icon: '&#9830;', desc: '本站赞助合作商家，内容保持独立' },
};

/* ---------------- API 服务商数据（15家） ---------------- */
const providers = [
  {
    id: 'midjourney-plus',
    name: 'Midjourney Plus',
    logo: 'MJ',
    category: 'drawing',
    categoryLabel: '绘图API',
    pricing: {
      textToImg: 0.055,
      imgToImg: 0.055,
      upscale: 0.022,
      vip: null,
      currency: 'USD',
      billingUnit: '张',
    },
    latency: { cn: '450ms', global: '220ms' },
    models: ['MJ-v6.1', 'MJ-Niji-6', 'MJ-raw'],
    support: { infiniteCanvas: true, img2img: true, openaiCompatible: false, region: '美西' },
    trialQuota: { amount: '25张', period: '新用户首月' },
    statusKeys: ['VERIFIED', 'TRIAL'],
    rating: 4.7,
    lastUpdated: '2026-07-15',
    description: '行业标杆级绘图API，出图质量极高，支持动漫、写实、插画等多种风格。通过中转接口提供，需关注合规风险。',
    url: 'https://www.midjourney.com',
    // 深度字段
    billingType: 'pay-as-you-go',
    concurrencyLimit: '中（≤20并发）',
    uptime: '99.2%',
    docQuality: '良',
    community: '活跃',
    supportLanguages: ['英文'],
    refundPolicy: '不支持',
    dataCompliance: '海外（数据出境）',
    compatibility: ['Midjourney原生'],
    notes: '出图质量业界顶尖，但仅支持英文Prompt。中转接口价格波动较大，建议月付。',
    tags: ['质量顶尖', '动漫', '插画', '写实'],
  },
  {
    id: 'stability-ai',
    name: 'Stability AI',
    logo: 'SA',
    category: 'drawing',
    categoryLabel: '绘图API',
    pricing: {
      textToImg: 0.018,
      imgToImg: 0.018,
      upscale: 0.008,
      vip: null,
      currency: 'USD',
      billingUnit: '张',
    },
    latency: { cn: '320ms', global: '150ms' },
    models: ['SDXL-1.0', 'SD-3.5', 'SD-Turbo'],
    support: { infiniteCanvas: true, img2img: true, openaiCompatible: false, region: '美西/欧' },
    trialQuota: { amount: '50张', period: '新用户' },
    statusKeys: ['VERIFIED', 'TRIAL'],
    rating: 4.3,
    lastUpdated: '2026-07-18',
    description: '开源模型生态最丰富的绘图API，模型可自托管，价格极低。SD Turbo 支持实时出图。',
    url: 'https://stability.ai',
    billingType: 'pay-as-you-go',
    concurrencyLimit: '高',
    uptime: '99.5%',
    docQuality: '优',
    community: '活跃',
    supportLanguages: ['英文'],
    refundPolicy: '7天内',
    dataCompliance: '海外',
    compatibility: ['Stability原生', 'ComfyUI'],
    notes: '开源生态丰富，可自托管降成本。SD 3.5 质量提升明显，但中文理解仍一般。',
    tags: ['开源', '低价', '可自托管', '速度快'],
  },
  {
    id: 'dalle3',
    name: 'DALL·E 3 (OpenAI)',
    logo: 'D3',
    category: 'drawing',
    categoryLabel: '绘图API',
    pricing: {
      textToImg: 0.040,
      imgToImg: null,
      upscale: null,
      vip: null,
      currency: 'USD',
      billingUnit: '张',
    },
    latency: { cn: '280ms', global: '120ms' },
    models: ['DALL·E-3', 'DALL·E-2'],
    support: { infiniteCanvas: false, img2img: false, openaiCompatible: true, region: '美西' },
    trialQuota: { amount: '5张', period: '新用户额度内' },
    statusKeys: ['VERIFIED', 'TRIAL'],
    rating: 4.5,
    lastUpdated: '2026-07-16',
    description: 'OpenAI 官方绘图API，理解语义能力强，支持复杂场景描述和中文Prompt。',
    url: 'https://openai.com',
    billingType: 'pay-as-you-go',
    concurrencyLimit: '中',
    uptime: '99.8%',
    docQuality: '优',
    community: '活跃',
    supportLanguages: ['中文', '英文'],
    refundPolicy: '按比例',
    dataCompliance: '海外（数据出境）',
    compatibility: ['OpenAI'],
    notes: '语义理解极强，适合复杂场景描述。不支持 img2img，价格中等偏高。',
    tags: ['语义强', '中文友好', 'OpenAI生态'],
  },
  {
    id: 'tongyi-wanxiang',
    name: '通义万相',
    logo: 'TW',
    category: 'drawing',
    categoryLabel: '绘图API',
    pricing: {
      textToImg: 0.012,
      imgToImg: 0.012,
      upscale: 0.006,
      vip: null,
      currency: 'CNY',
      billingUnit: '张',
    },
    latency: { cn: '150ms', global: '380ms' },
    models: ['Wanx-v2', 'Wanx-素描', 'Wanx-水彩'],
    support: { infiniteCanvas: true, img2img: true, openaiCompatible: false, region: '国内' },
    trialQuota: { amount: '100张', period: '新用户30天' },
    statusKeys: ['VERIFIED', 'TRIAL'],
    rating: 4.1,
    lastUpdated: '2026-07-18',
    description: '阿里通义系列绘图API，中文理解优秀，国风、水墨、动漫风格表现突出。',
    url: 'https://wanxiang.aliyun.com',
    billingType: 'pay-as-you-go',
    concurrencyLimit: '高',
    uptime: '99.6%',
    docQuality: '良',
    community: '一般',
    supportLanguages: ['中文', '英文'],
    refundPolicy: '7天内',
    dataCompliance: '国内备案',
    compatibility: ['阿里云原生'],
    notes: '中文场景理解好，国风/水墨风格有特色。国内访问速度快，合规安全。',
    tags: ['国风', '水墨', '中文友好', '国内合规'],
  },
  {
    id: 'openai',
    name: 'OpenAI',
    logo: 'OA',
    category: 'llm',
    categoryLabel: '大模型API',
    pricing: {
      inputPer1M: 2.50,
      outputPer1M: 10.00,
      vip: null,
      currency: 'USD',
      billingUnit: '1M tokens',
    },
    latency: { cn: '350ms', global: '150ms' },
    models: ['GPT-4.5', 'GPT-4o', 'GPT-4o-mini', 'o3-mini'],
    support: { infiniteCanvas: false, img2img: false, openaiCompatible: true, region: '美西' },
    trialQuota: { amount: '$5', period: '新用户3个月' },
    statusKeys: ['VERIFIED', 'TRIAL'],
    rating: 4.8,
    lastUpdated: '2026-07-14',
    description: '行业标杆大模型API，GPT-4.5 在推理、代码、创意写作方面表现顶尖。生态最完善。',
    url: 'https://platform.openai.com',
    billingType: 'pay-as-you-go',
    concurrencyLimit: '高',
    uptime: '99.9%',
    docQuality: '优',
    community: '极活跃',
    supportLanguages: ['中文', '英文', '多语言'],
    refundPolicy: '按比例',
    dataCompliance: '海外（数据出境）',
    compatibility: ['OpenAI'],
    notes: '行业标杆，生态完善。但国内访问需代理，且存在封号风险。GPT-4o-mini 性价比不错。',
    tags: ['行业标杆', '推理强', '代码', '生态完善'],
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    logo: 'DS',
    category: 'llm',
    categoryLabel: '大模型API',
    pricing: {
      inputPer1M: 0.15,
      outputPer1M: 0.60,
      vip: null,
      currency: 'CNY',
      billingUnit: '1M tokens',
    },
    latency: { cn: '80ms', global: '220ms' },
    models: ['DeepSeek-V3', 'DeepSeek-R1', 'DeepSeek-Coder-V2'],
    support: { infiniteCanvas: false, img2img: false, openaiCompatible: true, region: '国内' },
    trialQuota: { amount: '10元', period: '新用户' },
    statusKeys: ['VERIFIED', 'TRIAL'],
    rating: 4.6,
    lastUpdated: '2026-07-18',
    description: '国产性价比之王，DeepSeek-V3 性能接近 GPT-4o 但价格仅 1/20。R1 推理模型开源免费。',
    url: 'https://platform.deepseek.com',
    billingType: 'pay-as-you-go',
    concurrencyLimit: '高',
    uptime: '99.4%',
    docQuality: '良',
    community: '活跃',
    supportLanguages: ['中文', '英文'],
    refundPolicy: '7天内',
    dataCompliance: '国内备案',
    compatibility: ['OpenAI', 'Anthropic'],
    notes: '性价比极高，V3 综合能力强。但高峰期偶发延迟升高。国内合规，访问速度极快。',
    tags: ['性价比之王', '国产', '推理强', '开源'],
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    logo: 'AN',
    category: 'llm',
    categoryLabel: '大模型API',
    pricing: {
      inputPer1M: 3.00,
      outputPer1M: 15.00,
      vip: null,
      currency: 'USD',
      billingUnit: '1M tokens',
    },
    latency: { cn: '380ms', global: '160ms' },
    models: ['Claude-3.5-Sonnet', 'Claude-3.5-Haiku', 'Claude-3-Opus'],
    support: { infiniteCanvas: false, img2img: false, openaiCompatible: false, region: '美西' },
    trialQuota: { amount: '$5', period: '新用户' },
    statusKeys: ['VERIFIED', 'TRIAL'],
    rating: 4.7,
    lastUpdated: '2026-07-15',
    description: 'Claude 系列以长文本理解、安全性和逻辑推理著称。3.5-Sonnet 在代码和写作方面表现优异。',
    url: 'https://www.anthropic.com',
    billingType: 'pay-as-you-go',
    concurrencyLimit: '中',
    uptime: '99.7%',
    docQuality: '优',
    community: '活跃',
    supportLanguages: ['英文', '中文'],
    refundPolicy: '按比例',
    dataCompliance: '海外（数据出境）',
    compatibility: ['Anthropic原生'],
    notes: '长文本处理能力极强，安全性高。但仅支持英文文档，价格较高。需代理访问。',
    tags: ['长文本', '安全', '逻辑推理', '写作'],
  },
  {
    id: 'aliyun-bailian',
    name: '阿里百炼',
    logo: 'AL',
    category: 'llm',
    categoryLabel: '大模型API',
    pricing: {
      inputPer1M: 0.50,
      outputPer1M: 2.00,
      vip: null,
      currency: 'CNY',
      billingUnit: '1M tokens',
    },
    latency: { cn: '60ms', global: '280ms' },
    models: ['Qwen-2.5-Max', 'Qwen-2.5-72B', 'Qwen-2.5-Coder', 'Qwen-VL-Plus'],
    support: { infiniteCanvas: false, img2img: false, openaiCompatible: true, region: '国内' },
    trialQuota: { amount: '100万tokens', period: '新用户30天' },
    statusKeys: ['VERIFIED', 'TRIAL'],
    rating: 4.2,
    lastUpdated: '2026-07-18',
    description: '阿里通义千问系列模型，Qwen-2.5-Max 综合性能接近 GPT-4o。支持多模态（图文理解）。',
    url: 'https://bailian.aliyun.com',
    billingType: 'pay-as-you-go',
    concurrencyLimit: '高',
    uptime: '99.6%',
    docQuality: '良',
    community: '一般',
    supportLanguages: ['中文', '英文', '多语言'],
    refundPolicy: '7天内',
    dataCompliance: '国内备案',
    compatibility: ['OpenAI', 'Anthropic'],
    notes: '国内合规，速度快。Qwen-VL 支持图文理解。中文场景优化好。但部分高级功能文档不够详细。',
    tags: ['国内合规', '多模态', '中文', '速度快'],
  },
  {
    id: 'zhipu-glm',
    name: '智谱 GLM',
    logo: 'ZP',
    category: 'llm',
    categoryLabel: '大模型API',
    pricing: {
      inputPer1M: 0.50,
      outputPer1M: 1.50,
      vip: null,
      currency: 'CNY',
      billingUnit: '1M tokens',
    },
    latency: { cn: '70ms', global: '260ms' },
    models: ['GLM-4-Plus', 'GLM-4-Flash', 'GLM-4V', 'CodeGeeX-4'],
    support: { infiniteCanvas: false, img2img: false, openaiCompatible: true, region: '国内' },
    trialQuota: { amount: '50万tokens', period: '新用户' },
    statusKeys: ['VERIFIED', 'TRIAL'],
    rating: 4.0,
    lastUpdated: '2026-07-17',
    description: '智谱 GLM-4 系列在中文理解和代码生成方面表现不错。CodeGeeX 是专用代码模型。',
    url: 'https://open.bigmodel.cn',
    billingType: 'pay-as-you-go',
    concurrencyLimit: '中',
    uptime: '99.3%',
    docQuality: '良',
    community: '一般',
    supportLanguages: ['中文', '英文'],
    refundPolicy: '7天内',
    dataCompliance: '国内备案',
    compatibility: ['OpenAI'],
    notes: 'CodeGeeX 代码能力不错。GLM-4V 支持视觉理解。价格适中，但高峰期稳定性稍弱。',
    tags: ['代码', '中文', '视觉', '适中价格'],
  },
  {
    id: 'volcano-engine',
    name: '火山引擎',
    logo: 'VE',
    category: 'llm',
    categoryLabel: '大模型API',
    pricing: {
      inputPer1M: 0.50,
      outputPer1M: 2.00,
      vip: null,
      currency: 'CNY',
      billingUnit: '1M tokens',
    },
    latency: { cn: '55ms', global: '290ms' },
    models: ['Doubao-Pro', 'Doubao-Lite', 'Doubao-Vision', 'Doubao-Code'],
    support: { infiniteCanvas: false, img2img: false, openaiCompatible: true, region: '国内' },
    trialQuota: { amount: '50万tokens', period: '新用户' },
    statusKeys: ['VERIFIED', 'TRIAL'],
    rating: 4.1,
    lastUpdated: '2026-07-18',
    description: '字节跳动旗下豆包模型，Doubao-Pro 综合性能强，价格适中。背靠字节生态，多模态能力不错。',
    url: 'https://www.volcengine.com',
    billingType: 'pay-as-you-go',
    concurrencyLimit: '高',
    uptime: '99.5%',
    docQuality: '良',
    community: '一般',
    supportLanguages: ['中文', '英文'],
    refundPolicy: '7天内',
    dataCompliance: '国内备案',
    compatibility: ['OpenAI'],
    notes: '字节生态，多模态能力强。Pro 版本性价比高。但文档和社区活跃度一般。',
    tags: ['字节', '多模态', '国内', '性价比高'],
  },
  {
    id: 'moonshot',
    name: '月之暗面',
    logo: 'MS',
    category: 'llm',
    categoryLabel: '大模型API',
    pricing: {
      inputPer1M: 0.60,
      outputPer1M: 1.20,
      vip: null,
      currency: 'CNY',
      billingUnit: '1M tokens',
    },
    latency: { cn: '65ms', global: '250ms' },
    models: ['Kimi-K1.5', 'Kimi-K2', 'Kimi-Vision'],
    support: { infiniteCanvas: false, img2img: false, openaiCompatible: true, region: '国内' },
    trialQuota: { amount: '100万tokens', period: '新用户' },
    statusKeys: ['VERIFIED', 'TRIAL'],
    rating: 4.3,
    lastUpdated: '2026-07-18',
    description: 'Kimi 系列以超长上下文（200万字）和文件理解能力著称。Kimi-K2 在推理和代码方面表现优秀。',
    url: 'https://platform.moonshot.cn',
    billingType: 'pay-as-you-go',
    concurrencyLimit: '高',
    uptime: '99.5%',
    docQuality: '优',
    community: '活跃',
    supportLanguages: ['中文', '英文'],
    refundPolicy: '7天内',
    dataCompliance: '国内备案',
    compatibility: ['OpenAI'],
    notes: '超长上下文是核心优势，适合文档分析、长篇小说写作。社区活跃，文档完善。',
    tags: ['超长上下文', '文档分析', '中文', '活跃'],
  },
  {
    id: 'baidu-qianfan',
    name: '百度千帆',
    logo: 'BD',
    category: 'llm',
    categoryLabel: '大模型API',
    pricing: {
      inputPer1M: 0.50,
      outputPer1M: 2.00,
      vip: null,
      currency: 'CNY',
      billingUnit: '1M tokens',
    },
    latency: { cn: '70ms', global: '270ms' },
    models: ['ERNIE-4.0', 'ERNIE-3.5', 'ERNIE-Speed', 'ERNIE-Code'],
    support: { infiniteCanvas: false, img2img: false, openaiCompatible: true, region: '国内' },
    trialQuota: { amount: '100万tokens', period: '新用户' },
    statusKeys: ['VERIFIED', 'TRIAL'],
    rating: 3.9,
    lastUpdated: '2026-07-17',
    description: '百度文心系列大模型，ERNIE-4.0 在中文理解和知识问答方面表现不错。代码能力中等。',
    url: 'https://qianfan.baidu.com',
    billingType: 'pay-as-you-go',
    concurrencyLimit: '中',
    uptime: '99.3%',
    docQuality: '良',
    community: '一般',
    supportLanguages: ['中文', '英文'],
    refundPolicy: '7天内',
    dataCompliance: '国内备案',
    compatibility: ['OpenAI', '百度原生'],
    notes: '中文知识问答不错，但代码和创意写作能力一般。平台界面较复杂，上手门槛稍高。',
    tags: ['知识问答', '中文', '百度', '国内'],
  },
  {
    id: 'aliyun-speech',
    name: '阿里云语音',
    logo: 'AS',
    category: 'speech',
    categoryLabel: '语音API',
    pricing: {
      ttsPer1K: 0.24,
      asrPerHour: 2.00,
      vip: null,
      currency: 'CNY',
      billingUnit: '1K字符/小时',
    },
    latency: { cn: '120ms', global: '350ms' },
    models: ['CosyVoice-2', 'Paraformer-2', 'Sambert'],
    support: { infiniteCanvas: false, img2img: false, openaiCompatible: false, region: '国内' },
    trialQuota: { amount: '1000次', period: '新用户30天' },
    statusKeys: ['VERIFIED', 'TRIAL'],
    rating: 4.0,
    lastUpdated: '2026-07-18',
    description: '阿里云语音合成与识别服务，CosyVoice 支持情感控制和多语种，中文语音自然度高。',
    url: 'https://www.aliyun.com/product/nls',
    billingType: 'pay-as-you-go',
    concurrencyLimit: '高',
    uptime: '99.6%',
    docQuality: '良',
    community: '一般',
    supportLanguages: ['中文', '英文', '多语种'],
    refundPolicy: '7天内',
    dataCompliance: '国内备案',
    compatibility: ['阿里云原生'],
    notes: '中文语音合成自然度高，情感控制不错。语音识别在嘈杂环境准确率一般。',
    tags: ['语音合成', '中文', '情感', '国内'],
  },
  {
    id: 'tencent-speech',
    name: '腾讯云语音',
    logo: 'TS',
    category: 'speech',
    categoryLabel: '语音API',
    pricing: {
      ttsPer1K: 0.20,
      asrPerHour: 1.80,
      vip: null,
      currency: 'CNY',
      billingUnit: '1K字符/小时',
    },
    latency: { cn: '100ms', global: '330ms' },
    models: ['TTS-Plus', 'ASR-RealTime', 'VoiceClone'],
    support: { infiniteCanvas: false, img2img: false, openaiCompatible: false, region: '国内' },
    trialQuota: { amount: '1000次', period: '新用户' },
    statusKeys: ['VERIFIED', 'TRIAL'],
    rating: 3.9,
    lastUpdated: '2026-07-18',
    description: '腾讯云语音服务，TTS-Plus 支持多种音色和情感风格。VoiceClone 支持5秒克隆音色。',
    url: 'https://cloud.tencent.com/product/tts',
    billingType: 'pay-as-you-go',
    concurrencyLimit: '高',
    uptime: '99.5%',
    docQuality: '良',
    community: '一般',
    supportLanguages: ['中文', '英文', '多语种'],
    refundPolicy: '7天内',
    dataCompliance: '国内备案',
    compatibility: ['腾讯云原生'],
    notes: 'VoiceClone 音色克隆效果惊艳，但版权和使用规范需注意。语音合成音色选择丰富。',
    tags: ['音色克隆', '语音合成', '国内', '音色多'],
  },
  {
    id: 'kling-api',
    name: '可灵 API',
    logo: 'KL',
    category: 'drawing',
    categoryLabel: '绘图API',
    pricing: {
      textToImg: 0.035,
      imgToImg: 0.035,
      upscale: 0.015,
      vip: null,
      currency: 'CNY',
      billingUnit: '张',
    },
    latency: { cn: '180ms', global: '400ms' },
    models: ['Kling-2.0', 'Kling-1.6', 'Kling-Motion'],
    support: { infiniteCanvas: true, img2img: true, openaiCompatible: false, region: '国内' },
    trialQuota: { amount: '50张', period: '新用户' },
    statusKeys: ['VERIFIED', 'TRIAL', 'FLOATING'],
    rating: 4.4,
    lastUpdated: '2026-07-18',
    description: '快手可灵系列，以视频生成和动态绘图见长。Motion 模型支持动态风格转换。',
    url: 'https://kling.kuaishou.com',
    billingType: 'pay-as-you-go',
    concurrencyLimit: '中',
    uptime: '99.0%',
    docQuality: '良',
    community: '一般',
    supportLanguages: ['中文', '英文'],
    refundPolicy: '7天内',
    dataCompliance: '国内备案',
    compatibility: ['快手原生'],
    notes: '动态绘图和视频生成能力突出。价格近期有波动，建议关注。国内访问速度快。',
    tags: ['视频生成', '动态', '国内', '创意'],
  },
];

/* ---------------- 测评文章数据 ---------------- */
const reviews = [
  {
    id: 'r1',
    title: 'DeepSeek V3 vs GPT-4o：国产大模型能否一战？',
    category: 'llm',
    type: '横评',
    tags: ['DeepSeek', 'GPT-4o', '国产', '性价比'],
    summary: '从推理能力、代码生成、创意写作、中文理解四个维度，实测对比 DeepSeek V3 和 GPT-4o。结论：V3 在性价比上碾压，但复杂推理和创意写作仍略逊于 GPT-4o。',
    date: '2026-07-15',
    author: 'APIKnow 测评组',
    readTime: '12分钟',
  },
  {
    id: 'r2',
    title: 'Midjourney 中转 API 避坑指南：价格波动与封号风险实测',
    category: 'drawing',
    type: '避坑指南',
    tags: ['Midjourney', '中转', '风险', '价格'],
    summary: '实测 5 家 Midjourney 中转 API 的价格、稳定性和封号风险。发现 2 家存在明显价格波动，1 家近期出现封号潮。附风险评级和选购建议。',
    date: '2026-07-12',
    author: 'APIKnow 测评组',
    readTime: '8分钟',
  },
  {
    id: 'r3',
    title: '2026 年语音 API 横评：阿里云 vs 腾讯云 vs 海外服务商',
    category: 'speech',
    type: '横评',
    tags: ['语音合成', 'ASR', '阿里云', '腾讯云'],
    summary: '从语音自然度、识别准确率、延迟、价格、音色多样性五个维度，实测对比 5 家语音 API 服务商。结论：中文场景国内服务商更优，海外服务商多语种更强。',
    date: '2026-07-10',
    author: 'APIKnow 测评组',
    readTime: '10分钟',
  },
  {
    id: 'r4',
    title: 'Claude 3.5 Sonnet 深度测评：长文本与代码能力实测',
    category: 'llm',
    type: '深度测评',
    tags: ['Claude', '长文本', '代码', '安全性'],
    summary: 'Claude 3.5 Sonnet 在 20 万字长文本理解、复杂代码重构、多轮对话安全测试中的表现。实测结论：长文本处理业界最强，但中文输出偶尔有逻辑跳跃。',
    date: '2026-07-08',
    author: 'APIKnow 测评组',
    readTime: '15分钟',
  },
  {
    id: 'r5',
    title: '新手选购 AI API 的 10 条硬规则',
    category: 'llm',
    type: '新手教程',
    tags: ['新手', '避坑', '选购', '合规'],
    summary: '从计费方式、合规性、稳定性、退款政策、并发限制等 10 个维度，总结新手选购 AI API 的核心注意事项。附决策流程图。',
    date: '2026-07-05',
    author: 'APIKnow 测评组',
    readTime: '8分钟',
  },
  {
    id: 'r6',
    title: 'Kimi K2 超长上下文实测：200 万字文档分析能力',
    category: 'llm',
    type: '深度测评',
    tags: ['Kimi', '超长上下文', '文档分析', '月之暗面'],
    summary: '用真实长篇小说、法律合同、技术文档测试 Kimi K2 的 200 万字上下文处理能力。实测：检索准确率高，但长文本生成偶有重复。',
    date: '2026-07-03',
    author: 'APIKnow 测评组',
    readTime: '11分钟',
  },
  {
    id: 'r7',
    title: '绘图 API 额度消耗测算：一张图到底花多少钱？',
    category: 'drawing',
    type: '教程',
    tags: ['绘图', '额度', '测算', '成本'],
    summary: '详细拆解 Midjourney、DALL·E、SDXL、通义万相等 6 家绘图 API 的计费模型，按不同使用场景（批量出图、高清放大、风格迭代）测算真实成本。',
    date: '2026-06-28',
    author: 'APIKnow 测评组',
    readTime: '9分钟',
  },
  {
    id: 'r8',
    title: 'OpenAI API 封号风险与应对策略：2026 年最新经验',
    category: 'llm',
    type: '避坑指南',
    tags: ['OpenAI', '封号', '风险', '合规'],
    summary: '2026 年 OpenAI 封号政策最新变化，从 IP 地区、支付方式、使用频率、内容合规等维度分析封号原因，附预防策略和替代方案。',
    date: '2026-06-25',
    author: 'APIKnow 测评组',
    readTime: '10分钟',
  },
  {
    id: 'r9',
    title: '可灵 Kling 2.0 视频生成 API 实测：动态绘图新标杆',
    category: 'drawing',
    type: '深度测评',
    tags: ['可灵', 'Kling', '视频生成', '动态绘图'],
    summary: '可灵 Kling 2.0 在视频生成、动态风格转换、运动一致性方面的实测。结论：视频生成质量国内顶尖，但生成速度较慢，适合非实时场景。',
    date: '2026-06-20',
    author: 'APIKnow 测评组',
    readTime: '13分钟',
  },
  {
    id: 'r10',
    title: '智谱 GLM-4 vs 阿里 Qwen-2.5：国产大模型双雄对决',
    category: 'llm',
    type: '横评',
    tags: ['智谱', 'GLM', '阿里', 'Qwen', '国产'],
    summary: '从代码能力、中文理解、数学推理、多模态四个维度横评 GLM-4-Plus 和 Qwen-2.5-Max。结论：Qwen 综合能力更强，GLM 代码 niche 更突出。',
    date: '2026-06-18',
    author: 'APIKnow 测评组',
    readTime: '11分钟',
  },
];

/* ---------------- 费用计算器数据 ---------------- */
const calcModels = {
  llm: {
    name: '大模型对话',
    unit: 'tokens',
    subTypes: {
      'input':  { label: '输入（提问）', defaultRatio: 0.7 },
      'output': { label: '输出（回复）', defaultRatio: 0.3 },
    },
    providers: [
      { id: 'openai', name: 'OpenAI GPT-4o', input: 2.50, output: 10.00, currency: 'USD' },
      { id: 'deepseek', name: 'DeepSeek V3', input: 0.15, output: 0.60, currency: 'CNY' },
      { id: 'anthropic', name: 'Claude 3.5', input: 3.00, output: 15.00, currency: 'USD' },
      { id: 'aliyun', name: '阿里 Qwen-2.5', input: 0.50, output: 2.00, currency: 'CNY' },
      { id: 'zhipu', name: '智谱 GLM-4', input: 0.50, output: 1.50, currency: 'CNY' },
      { id: 'moonshot', name: '月之暗面 Kimi', input: 0.60, output: 1.20, currency: 'CNY' },
      { id: 'baidu', name: '百度 ERNIE-4', input: 0.50, output: 2.00, currency: 'CNY' },
      { id: 'volcano', name: '火山 Doubao', input: 0.50, output: 2.00, currency: 'CNY' },
    ],
  },
  drawing: {
    name: '图像生成',
    unit: '张',
    subTypes: {
      'text-to-img':  { label: '文生图', defaultRatio: 1.0 },
      'img-to-img':   { label: '图生图', defaultRatio: 0.0 },
      'upscale':      { label: '高清放大', defaultRatio: 0.0 },
    },
    providers: [
      { id: 'mj', name: 'Midjourney', textToImg: 0.055, imgToImg: 0.055, upscale: 0.022, currency: 'USD' },
      { id: 'sd', name: 'Stability AI', textToImg: 0.018, imgToImg: 0.018, upscale: 0.008, currency: 'USD' },
      { id: 'dalle', name: 'DALL·E 3', textToImg: 0.040, imgToImg: null, upscale: null, currency: 'USD' },
      { id: 'wanxiang', name: '通义万相', textToImg: 0.012, imgToImg: 0.012, upscale: 0.006, currency: 'CNY' },
      { id: 'kling', name: '可灵', textToImg: 0.035, imgToImg: 0.035, upscale: 0.015, currency: 'CNY' },
    ],
  },
  speech: {
    name: '语音服务',
    unit: '次',
    subTypes: {
      'tts': { label: '语音合成 (TTS)', defaultRatio: 0.6 },
      'asr': { label: '语音识别 (ASR)', defaultRatio: 0.4 },
    },
    providers: [
      { id: 'aliyun', name: '阿里云语音', tts: 0.24, asr: 2.00, currency: 'CNY' },
      { id: 'tencent', name: '腾讯云语音', tts: 0.20, asr: 1.80, currency: 'CNY' },
    ],
  },
};

/* ---------------- 热门标签 ---------------- */
const hotTags = ['性价比', '国产', '避坑', '新手', '中转', '封号', '视频生成', '长文本', '代码', '中文'];

/* ---------------- 导航数据 ---------------- */
const navItems = [
  { label: '首页', href: './', id: 'home' },
  { label: 'API 比价', href: 'comparison.html', id: 'comparison' },
  { label: '费用计算器', href: 'calculator.html', id: 'calculator' },
  { label: '测评中心', href: 'review.html', id: 'review' },
];

/* ---------------- 30秒选方向数据 ---------------- */
const quickGuides = [
  {
    icon: '&#127912;',
    title: '按场景选 API',
    desc: '绘图/大模型/语音，按业务场景缩小范围',
    link: 'comparison.html?category=drawing',
    accent: '#c9892e',
  },
  {
    icon: '&#128176;',
    title: '找性价比 API',
    desc: '按量计费、阶梯价、套餐，按预算选最优',
    link: 'comparison.html?sort=price-asc',
    accent: '#4a7c59',
  },
  {
    icon: '&#127807;',
    title: '新手试用 API',
    desc: '免费额度、试用期、避坑指南先看',
    link: 'comparison.html?status=TRIAL',
    accent: '#4a7c9b',
  },
  {
    icon: '&#128214;',
    title: '看 API 实测',
    desc: '横评报告、稳定性、风险边界先看',
    link: 'review.html',
    accent: '#a94442',
  },
];

const hardRules = [
  '中转 API 有风险：存在封号、断供、价格飞涨风险，重要业务建议官方直签。',
  '不要只看单价：需综合考虑延迟、稳定性、并发限制、文档质量、售后支持。',
  '免费额度有期限：多数试用期仅 7-30 天，到期后价格可能大幅变化。',
  '关注数据合规：国内业务优先选备案服务商，避免数据出境合规风险。',
  '推荐不等于永久稳定：购买前仍建议看近期公告、测评和用户反馈。',
];
